# -*- coding: utf-8 -*-
"""figure-data-structure-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHZBqs1DGWeYccZN7C5x29-mfgU_QYVF
"""

# Programmer Bhavesh Padharia

# The Figure Data Structure

# Follow Me : www.padharia.in

import plotly.express as px

fig = px.line(x=["a","b","c"], y= [1,2,3], title = "Sample figure")

fig.show()